# Kapittel 5

In [8]:
"""
Dette skriptet rekkereduserar ei matrise, typisk 
totalmatrisa til eit lineært likningssystemt, til 
redusert trappeform og skriv resultatet til skjerm.
"""

# Importerar NumPy og SymPy
import numpy as np
import sympy

# Sett antall desimalar vi skriv til skjerm for NumPy
np.set_printoptions(precision=4, floatmode='fixed', suppress=True)

# Tilordnar totalmatrisa 
T = np.array([[5, 1, 1, -2, 2],
              [1, -1, 1, 7, 30],
              [2, 1, 0, -5, -16],
              [2, 0, 1, 3, 17]])


R = sympy.Matrix(T).rref()[0]    # Rekkereduserar
R = np.array(R)                  # Konverterar til array
print(R)                         # Skriv til skjerm

[[1 0 0 0 1]
 [0 1 0 0 2]
 [0 0 1 0 3]
 [0 0 0 1 4]]


In [9]:
"""
Her reknar vi ut produktet av to kvadratiske 
matriser - på ulike måtar.
"""

# Importerar NumPy
import numpy as np

# Sett antall desimalar vi skriv til skjerm for NumPy
np.set_printoptions(precision=4, floatmode='fixed', suppress=True)

# Tilordnar to matriser
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
B = np.array([[-2, -1, 0],
              [0, 1, 0],
              [7, -2, 1]])

# Med *-produkt
print('A*B:')
print(A*B)
print('B*A:')
print(B*A)

# Med @-produkt
print('A@B:')
print(A@B)
print('B@A:')
print(B@A)

# Med multiply
print('multiply(A, B):')
print(np.multiply(A, B))


# Med matmul
print('matmul(A, B):')
print(np.matmul(A, B))


A*B:
[[ -2  -2   0]
 [  0   5   0]
 [ 49 -16   9]]
B*A:
[[ -2  -2   0]
 [  0   5   0]
 [ 49 -16   9]]
A@B:
[[ 19  -5   3]
 [ 34 -11   6]
 [ 49 -17   9]]
B@A:
[[ -6  -9 -12]
 [  4   5   6]
 [  6  12  18]]
multiply(A, B):
[[ -2  -2   0]
 [  0   5   0]
 [ 49 -16   9]]
matmul(A, B):
[[ 19  -5   3]
 [ 34 -11   6]
 [ 49 -17   9]]


In [10]:
"""
I dette skriptet tilordnar vi ei kvadratisk matrise 
og inverterar ho.
Inversmatrisa blir skriven til skjerm.
"""

# Importerar numpy
import numpy as np

# Sett antall desimalar vi skriv til skjerm for NumPy
np.set_printoptions(precision=4, floatmode='fixed', suppress=True)

# Tilordnar matrisa
A = np.array([[3, -7, 1],
              [3, 3, -1],
              [1, 1, 1]])

# Inverterar og skriv resultatet til skjerm
Ainv = np.linalg.inv(A)
print(Ainv)

# Sjekkar at produktet blir I
Prod = np.matmul(A, Ainv)
print(Prod)

[[ 0.1000  0.2000  0.1000]
 [-0.1000  0.0500  0.1500]
 [ 0.0000 -0.2500  0.7500]]
[[ 1.0000 -0.0000  0.0000]
 [-0.0000  1.0000  0.0000]
 [-0.0000  0.0000  1.0000]]


In [11]:
"""
I dette skriptet forsøker vi å løyse eit likningssystem 
ved å invertere koeffisientmatrisa.
Dette gir berre meining når vi har like mange likningar 
og ukjende - altså  når koeffisientmatrisa er kvadratisk.
"""

# Importerar numpy
import numpy as np

# Sett antall desimalar vi skriv til skjerm for NumPy
np.set_printoptions(precision=4, floatmode='fixed', suppress=True)

# Tilordnar matrisa
A = np.array([[1, 2, 0, 0],
             [1, -2, 1, 0],
             [0, 1, -2, 1],
             [0, 0, 1, -3]])

# Hoegresida (som vektor)
b = np.array([3, 7, np.pi, 2+3j])

# Reknar ut løysinga og skriv ho til skjerm
Ainv = np.linalg.inv(A)
x = np.matmul(Ainv, b)
print(np.round(x, 3))

[ 6.6970+0.3530j -1.8490-0.1760j -3.3940-0.7060j -1.7980-1.2350j]


In [12]:
"""
Dette skriptet testar kandidatar til reknereglar for matriser. For å teste 
brukar vi 3*3-matriser med tilfeldige tal mellom -5 og 5.
"""

# Importerar NumPy
import numpy as np

# Lagar matriser med tilfeldige tal
A = 10*(np.random.rand(3, 3) - 0.5*np.ones((3,3)))
B = 10*(np.random.rand(3, 3) - 0.5*np.ones((3,3)))

# Venstresida i "rekneregelen"
VS = A + B
# Høgresida
HS = B + A

# Skriv differansen til skjerm - for å sjå om det blir nullmatrisa
print(VS - HS)  

[[0.0000 0.0000 0.0000]
 [0.0000 0.0000 0.0000]
 [0.0000 0.0000 0.0000]]


In [13]:
""" Skriptet finn eigenverdiar og eigenvektorar til ei matrise. 
I tillegg til å skrive ut desse, sjekkar også skriptet om
den karakteristiske likninga, det(A - \lambda I) = 0, er
oppfylt - og at V^{-1} A V, der V har eigenvektorane som
søyler, blir ei diagonalmatrise med eigenverdiane langs 
diagonalen.
"""

# Importerar NumPy
import numpy as np

# Sett antall desimalar vi skriv til skjerm for NumPy
np.set_printoptions(precision=4, floatmode='fixed', suppress=True)

# Tilordnar matrisa
A = np.array([[4, 6, 6],
              [-2, 5, 5],
              [2, -3, -3]])

# Finn eigenverdiar og eigenvektorar
Lambda, V = np.linalg.eig(A)

#Skriv verdiane til skjerm
print('Vektor med eigenverdiar:')
print(Lambda)
print('Matrise med eigenvektorar:')
print(V)

# Sjekkar den karakterstiske likninga
EigenVerdi = Lambda[0]
Rot = np.linalg.det(A - EigenVerdi*np.eye(3)) 
print('VS i karakteristisk likning: ', Rot)

# Sjekkar diagonaliseringa
Vinv = np.linalg.inv(V)            # Inverterar 
D = np.matmul(Vinv, np.matmul(A, V))      
print('Produktet Vinv A V: ')
print(np.round(D, 4))      

Vektor med eigenverdiar:
[4.0000 0.0000 2.0000]
Matrise med eigenvektorar:
[[-0.8165 -0.0000 -0.3889]
 [ 0.4082  0.7071  0.7130]
 [-0.4082 -0.7071 -0.5834]]
VS i karakteristisk likning:  -3.197442310920445e-14
Produktet Vinv A V: 
[[ 4.0000 -0.0000 -0.0000]
 [-0.0000  0.0000 -0.0000]
 [ 0.0000 -0.0000  2.0000]]


<>:1: SyntaxWarning: invalid escape sequence '\l'
<>:1: SyntaxWarning: invalid escape sequence '\l'
/tmp/ipykernel_74140/4068274401.py:1: SyntaxWarning: invalid escape sequence '\l'
  """ Skriptet finn eigenverdiar og eigenvektorar til ei matrise.


In [14]:
"""
Dette skriptet definerar funksjonar som implementerar 
dei tre typane rekkeoperasjonar vi kan gjere på ei matrise.
Den brukar så desse funksjonane til å rekkeoperere på 
ei gitt matrise.
"""

# Importerar NumPy
import numpy as np

# Sett antall desimalar vi skriv til skjerm for NumPy
np.set_printoptions(precision=4, floatmode='fixed', suppress=True)

# Tilordnar ei matrise
A = np.array([[1, 2, 3],
              [4, 5, 6]])
             
# Funksjon som gangar rekke n med talet k
def GangeRekke(A, n, k):
    B = np.copy(A)
    B[n, :] = k*A[n, :]
    return B

# Funksjon som byter om på rekke m og n
def ByteRekker(A, m, n):
    B = np.copy(A)
    B[m, :] = A[n, :]
    B[n, :] = A[m, :]
    return B    

# Funksjon som legg k gonger rekke m til rekke n
def LeggeTilMult(A, m, n, k):
    B = np.copy(A)
    B[n, :] = A[n, :] + k*A[m, :]
    return B

# Utfører rekkeoperasjonar på A
A1 = LeggeTilMult(A, 0, 1, -4)
print(A1)

A2 = GangeRekke(A1, 1, -1/3)
print(A2)

A3 = LeggeTilMult(A2, 1, 0, -2)
print(A3)            
             

[[ 1  2  3]
 [ 0 -3 -6]]
[[1 2 3]
 [0 1 2]]
[[ 1  0 -1]
 [ 0  1  2]]
