# Kapittel 17

In [24]:
### Bakoverfase.m

import numpy as np

def Bakoverfase(A, LeiarVektor):
    
    # Denne funksjonen tar utgangspunkt i ei matrise på
    # trappeform og ein vektor med søylenummera til alle
    # leiande tal. Den sørger for at alle leiande tal blir
    # éin og alle tal over desse blir null.
    # Input: 
    # A - matrise på trappeform
    # LeiarVektor - vektor med nummeret på leiande søyler
    # Elementa i LeiarVektor må komme i stigande rekkefølge.

    M = np.copy(A)
    
    # Kopierer matrisa og finn formatet
    m = A.shape[0]
    n = A.shape[1]
    
    # Bestemmer talet på leiande tal
    l = len(LeiarVektor)
    
    # Går gjennom dei leiande tala - nedanfrå
    for rekke in range(l-1, -1, -1):
      soeyle = LeiarVektor[rekke]               # Den aktuelle søyla
      Blokk = M[0:rekke+1, soeyle:n]            # Hentar ut blokk
      kInv = Blokk[rekke, 0]                    # Det leiande talet
      Blokk = GongeRekke(Blokk, 1/kInv, rekke)  # Set dette til 1
      # Gjer tala over det leiande talet til null
      for p in range(0, rekke):
        k = -Blokk[p, 0]
        Blokk = LeggeTilMult(Blokk, k, rekke, p)
      M[0:rekke+1, soeyle:n] = Blokk             # Oppdaterer matrisa    

    return M

###

# ByteRekker.m

def ByteRekker(A, m, n):
    
    # Funksjon som byter om to rekker i ei matrise
    # Input:
    # A: Matrisa som skal endrast.
    # m og n: Rekkene som skal bytast om.
    
    M = np.copy(A)
    
    M[[m, n],:] = A[[n, m],:]

    return M
    
###
    
# GongeRekker.m
    
def GongeRekke(A, k, m):
    
    # Funksjon som gongar ei rekke i ei matrise
    # med eit tal ulik null
    # Input:
    # A: Matrisa som skal endrast.
    # k: Talet det skal gongast med.
    # m: Rekka som skal gongast med dette talet.
    
    if abs(k) < 1e-14:
      print('Talet får ikkje vere null.')
      return
    
    M = np.copy(A)
    M[m, :] = k * A[m, :]

    return M

###

# LeggeTilMult.m

def LeggeTilMult(A, k, m, n):

    # Funksjon som legg eit multiplum av
    # ei rekke til ei anna rekke i ei matrise.
    # Input:
    # A: Matrisa som skal endrast.
    # k: Talet det skal gongast med.
    # m: Rekka som skal gongast med k og leggast til n.
    # n: Rekka som vi skal legge til k gongar rekke m.
    
    M = np.copy(A)

    M[n, :] = A[n, :] + k*A[m, :]

    return M

###

# RTF.m

def RTF(A):

    # Funksjon som rekkereduserer ei matrise til redusert
    # trappeform. Funksjonen brukr først funksjonsfila
    # Trappeform, som reduserer matrisa til ei trappeform.
    # Kvart steg i denne prosessen blir utført i funksjonsfila
    # Trappesteg. Når matrisa er redusert til trappeform,
    # går vi vidare til redusert trappeform med funksjonen
    # Bakoverfase. Fleire av desse funksjonsfilene brukar
    # funksjonfiler som implementerer dei tre elementære
    # rekkeoperasjonane. Desse er:
    # ByteRekker
    # GongeRekke
    # LeggeTilMult
    
    # Får matrisa på trappeform og finn søylene med leiande tal
    M, LeiarVektor = Trappeform(A)
    
    # Finn talet på leiande tal
    l = len(LeiarVektor)
    
    # Viss der er leiande tal: Utfører "bakoverfasen",
    # som går ut på å sette alle leiande tal til 1 og
    # gjere alle tal over desse til null.
    if l > 0:
      M = Bakoverfase(M, LeiarVektor)

    return M

###

# Trappeform.m

def Trappeform(A):
    
    # Funksjon som reduserer ei matrise til ei trappeform.
    # Funksjonen lagar også ein vektor med søylenummera
    # til søylene med leiande tal.
    
    # Finn formatet på matrisa
    m = A.shape[0]
    n = A.shape[1]
    
    # Kopierer matrisa
    M = np.copy(A)
    
    # Initierer vektoren med søylenummera for dei leiande tala
    LeiarVektor = []
    # Set rekkenummeret til éin
    rekke = 0
    # Går gjennom kvar søyle i matrisa og rekkereduserer for
    # kvar undermatrise
    
    for soeyle in range(0, n):
      # Hentar ut relevant underblokk av matrisa
      Blokk = M[rekke:m, soeyle:n]
      # Rekkeopererer på blokka slik at første søyle får
      # rett struktur
      # Undersøker også om søyla har leiande tal
      Blokk, leiar = Trappesteg(Blokk, m-rekke)
      # Oppdaterer dersom søyla har leiande tal
      if leiar == 1:
        # Oppdaterer vektor med leiande tal
        LeiarVektor.append(soeyle)
        # Oppdaterer den store matrisa
        M[rekke:m, soeyle:n] = Blokk
        # Oppdaterer rekketalet
        rekke = rekke+1
    
    return M, LeiarVektor

###

# Trappesteg.m

def Trappesteg(A, m):

    # Funksjon som omstrukturerer første søyle i ei matrise
    # slik at dette blir første steg mot å få matrisa på
    # trappeform. Input er matrisa som skal rekkereduserast
    # og talet på rekker i denne. Output er den 
    # modifiserte matrisa og ein indeks som er 1 dersom
    # søyla har leiande tal og 0 viss ikkje.
    # Input:
    # A - Matrisa som skal rekkereduserast
    # m - talet på rekker i matrisa
    
    # Kopierer matrisa
    M = np.copy(A)
    
    # Leitar etter eit tal ulik null i søyle 1
    indeks = 0
    while indeks <= m-1 and np.abs(A[indeks, 0]) < 1e-14:
      indeks = indeks+1
    
    # Viss det er ei rein nullsøyle
    if indeks == m:
     leiar = 0             # Set at søyla ikkje har leiande tal
     return None, leiar    # Går ut av funksjonsfila
    
    # Set at søyla har eit leiande tal
    leiar = 1
    
    # Sørger for å ha tal ulik null oppe til venstre
    if indeks > 0:
      M = ByteRekker(M, 0, indeks)
    
    # Gjer alle tala under det leiande talet til null
    m11 = M[0, 0]
    for indeks in range(1, m):
      # Finn talet vi skal gonge med
      k = -M[indeks, 0]/m11
      # Legg til slik at vi får null
      M = LeggeTilMult(M, k, 0, indeks)
    
    return M, leiar

###

# Test

A = np.array([[1, 2, 3, -1], [4, 5, 6, 3], [7, 8, 9, 5]])
print(A)

B = RTF(A)
print(B)

C = np.array([[1, -1, -2, 4], [2, -1, -1, 2], [2, 1, 4, 16]])
print(C)

D = RTF(C)
print(D)

[[ 1  2  3 -1]
 [ 4  5  6  3]
 [ 7  8  9  5]]
[[ 1  0 -1  0]
 [ 0  1  2  0]
 [ 0  0  0  1]]
[[ 1 -1 -2  4]
 [ 2 -1 -1  2]
 [ 2  1  4 16]]
[[  1   0   0  24]
 [  0   1   0  72]
 [  0   0   1 -26]]
